version: "3"
services:
  app:
    container_name: emp_final
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql_service
  mysql_service:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: my_native_password
      MYSQL_DATABASE: 'mydatabase'
    restart: on-failure
    ports: 
      - "3366:3306"
